### ISSUE TITLE
Jetson Nano

### ISSUE THREAD

**Issue by dd0vs** [matiasdelellis/pdlib-min-test-suite#2]
Hello, 
got it compiled on a Jetson Nano. The make php-test runs for Big Bang Theory.JPG.
after output: "Processing file: input/Big Bang Theory.PNG" php are killed after about 15min. The same with python.
Is there any chance for scaling the memory demand?
Regards
Harald

**Comment by matiasdelellis** [comment]
Hi @dd0vs 
This literally depends on the size of the image and thes seems that it are very large. 

For now shrinking images.. :)

> [matias@ideapad pdlib-min-test-suite]$ convert input/Big\ Bang\ Theory.jpg -resize 1024x1024 input/Big\ Bang\ Theory\ 2 .jpeg 

However, I have to add a routine that temporarily reduces them before analyzing.

Thanks for report..

**Comment by dd0vs** [comment]
Hello Matias, thanks for prompt reply. The jpeg files was processed, but the png not. Resizing to 1024x1024 leads to a larger file?
Regards
Harald

**Comment by matiasdelellis** [comment]
No .. the PNG image is the same converted image.. You should also shrink it. :wink:

**Comment by dd0vs** [comment]
Hello, the Big Bang Theory.png was converted to 512x512, and was processed very fast! File size was onyl a little smaller than the original

**Comment by matiasdelellis** [comment]
Great.. :smile:

Yes ... both the memory consumption and the processing time depend directly on the image area.

**Comment by matiasdelellis** [comment]
Close with last commit on master.. :wink:

**Comment by dd0vs** [comment]
Ok, now it runs on Jetson Nano in 16,792s ! But in the jpg one face is not found.
I plan to make use of it on my nextcloud family archive, but all the images are often larger than 1MB.
But thanks for your support!
Regards
Harald DD0VS
