### ISSUE TITLE
NextCloudPi instance, no faces in jpg and only 4 in png detected

### ISSUE THREAD

**Issue by jimaldon** [matiasdelellis/pdlib-min-test-suite#3]
Hi, here's the output of `make php-test`
```
php scripts/face_detect.php
Welcome to pdlib min test suite for Facerecognition app...

First we try to open the models... Done

Processing file: input/Big Bang Theory.jpg
Number of faces detected: 0
Processing file: input/Big Bang Theory.png
Number of faces detected: 4
Face landmarks... Done
Face descriptor... Done
Face landmarks... Done
Face descriptor... Done
Face landmarks... Done
Face descriptor... Done
Face landmarks... Done
Face descriptor... Done

```
Does this mean my pdlib installation is flawed? 

EDIT: My pi has 4GB of RAM so it meets the hardware requirements here: https://github.com/matiasdelellis/facerecognition/wiki/Requirements-and-Limitations

**Comment by matiasdelellis** [comment]
Hi @jimaldon 
About pdlib, there is not much magic. So, just run the python test too. This should return the same result, and if so, pdlib is fine. Then ensure that that dlib was compiled with jpeg support.

**Comment by matiasdelellis** [comment]
Hi @jimaldon 
Please test again with updated tests. The images were very small, and the python test enlarged the image unnecessarily. :disappointed: 

Now it should work and get the same results between all tests.. :sweat_smile:
