### ISSUE TITLE
Number of faces incorrect / cannot run tests without CLI sapi

### ISSUE THREAD

**Issue by ggeorgg** [matiasdelellis/pdlib-min-test-suite#5]
Hi,
I want to install the nextcloud face recognition app and tried to setup my system. I stumbled accross some problems. 

A call of the python script itself works more or less fine:
```
georg@Quetzal:~/pdlib-min-test-suite> python3 scripts/face_detect.py
Welcome to pdlib min test suite for Facerecognition app

First we try to open the models... Done

Processing file: input/Big Bang Theory.jpg
Number of faces detected: 3
Face landmarks... Done
Face descriptor... Done
Face landmarks... Done
Face descriptor... Done
Face landmarks... Done
Face descriptor... Done
Processing file: input/Big Bang Theory.png
Number of faces detected: 7
Face landmarks... Done
Face descriptor... Done
Face landmarks... Done
Face descriptor... Done
Face landmarks... Done
Face descriptor... Done
Face landmarks... Done
Face descriptor... Done
Face landmarks... Done
Face descriptor... Done
Face landmarks... Done
Face descriptor... Done
georg@Quetzal:~/pdlib-min-test-suite> 
```
Whereas as call to "make php-test" does not give the expected result:
```
georg@Quetzal:~/pdlib-min-test-suite> make php-test
php scripts/face_detect.php
Welcome to pdlib min test suite for Facerecognition app...

First we try to open the models... Done
georg@Quetzal:~/pdlib-min-test-suite> 
```
So my first question is: Why does the python script only recognize 3 faces in the jpg file instead of 7?
The second question is: Why does the make php-test does not give any results und justs says "Done"? Where would I have to look to find out what is going wrong?

I previously installed dlib according to [https://github.com/davisking/dlib](https://github.com/davisking/dlib) and ran `./dtest --runall` without errors.
Afterwards I installed pdlib according to [https://github.com/goodspb/pdlib](https://github.com/goodspb/pdlib). Unfortunately, one problem remained here. If I run "make test" I get the following output:
```
georg@Quetzal:~/pdlib> make test

Build complete.
Don't forget to run 'make test'.

ERROR: Cannot run tests without CLI sapi.
georg@Quetzal:~/pdlib>
```
I guess this is a configuration / setup related error. Could you help me with this topic? If no, can you point me somewhere else, where I can get help? May this be the reason, why the "make test" does not do anything?

If you need further information, please let me know.

Thank you very much
Best regards
Georg

**Comment by matiasdelellis** [comment]
> So my first question is: Why does the python script only recognize 3 faces in the jpg file instead of 7?

Just they are two different images, and therefore they give different results.

> The second question is: Why does the make php-test does not give any results und justs says "Done"?

The done is about the opening of the models. but I wouldn't know because it doesn't show anything else, it's strange .. :thinking: 

> Where would I have to look to find out what is going wrong?

I'm investigating .. Make sure you are not running out of memory and the kernel kills the process.

**Comment by ggeorgg** [comment]
Yes, they are two different images, but both of them show 7 faces. 
According to [https://github.com/matiasdelellis/pdlib-min-test-suite#how-to-test-dlib](https://github.com/matiasdelellis/pdlib-min-test-suite#how-to-test-dlib) the output should show, that in each picture 7 images are found. How is this possible? 
Where are the "parameters" defined in this python script? Maybe I still did something wrong during the installation...

**Comment by matiasdelellis** [comment]
This due the readme shows the result of when the images were bigger!. Then I reduced it because some people had memory problems.. :sweat_smile: 

If you haven't learned this yet, when images are small, you lose some ability to find faces.. If you increase the size of the images, you will find more faces, but it will be slower, and it will consume more memory.. So we can say that this is the most important configuration. :wink: 

Now I update the readme to show the current results. :grimacing: 

Thanks.. :wink:

**Comment by matiasdelellis** [comment]
Hi @ggeorgg 
Just update Readme..

**Comment by ggeorgg** [comment]
Great, now it makes sense to me!
I also increased from php memory limit from 2048 to 4096 and the nextcloud app now recognize all 7 faces in both images.
Thanks a lot for this great app! I guess we can close this issue then, as you already updated the readme ([https://github.com/matiasdelellis/pdlib-min-test-suite/commit/fe6390508e1eacd181cf3ca1ffcbc11747f38e1e](https://github.com/matiasdelellis/pdlib-min-test-suite/commit/fe6390508e1eacd181cf3ca1ffcbc11747f38e1e)).
I think the second part regarding the CLI sapi is not that relevant.

Thanks for this great work! Keep going 👍
